# Generated by Django 3.2.4 on 2022-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='like',
            field=models.CharField(db_index=True, max_length=5, verbose_name='favorite'),
        ),
    ]
